### ISSUE TITLE
Add gif to show the plugin in action

### ISSUE THREAD

**Issue by hamxabaig** [inkarkat/vim-LineJuggler#1]
A gif on the readme would be very nice to have!

**Comment by inkarkat** [comment]
The plugin consists of several small mappings, each of which can be tried out on any arbitrary buffer contents to see its effects. Of course, there never is too much documentation (unless it's too hard to locate then), but I think the cost-benefit ratio is not worth doing it for this plugin. Nobody has contributed a set of GIFs, so I think I'll finally close this.

I hope you're still happy with the plugin :-)
